using System.Runtime.CompilerServices;
// <auto-generated>
// This file should only contain assembly level attributes.
// Do not add any class or struct definitions as it may disable the ability of the tool to
// update the file.
// </auto-generated>

using System;

[assembly: InternalsVisibleTo("databaseEntity.Tests")]
[assembly: InternalsVisibleTo("databaseEntity.Explorables")]
[assembly: InternalsVisibleTo("databaseEntity.Tests1")]
[assembly: InternalsVisibleTo("databaseEntity.Tests2")]

