//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class bestStrategy
    {
        public string stockCode { get; set; }
        public string timeFrame { get; set; }
        public string strategyCode1 { get; set; }
        public string strategyCode2 { get; set; }
        public string strategyCode3 { get; set; }
    
        public virtual stockCode stockCode1 { get; set; }
    }
}
