//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class exchangeDetail
    {
        public short orderId { get; set; }
        public string code { get; set; }
        public string marketCode { get; set; }
        public string address { get; set; }
        public string goTrue { get; set; }
        public string goFalse { get; set; }
        public string notes { get; set; }
        public string culture { get; set; }
        public Nullable<bool> isEnabled { get; set; }
    }
}
