//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class financialModel
    {
        public string name { get; set; }
        public string nameVN { get; set; }
        public string nameUS { get; set; }
        public string model { get; set; }
        public string sector { get; set; }
    }
}
