//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class investorStock
    {
        public string stockCode { get; set; }
        public string portfolio { get; set; }
        public System.DateTime buyDate { get; set; }
        public decimal qty { get; set; }
        public decimal buyAmt { get; set; }
    
        public virtual portfolio portfolio1 { get; set; }
        public virtual stockCode stockCode1 { get; set; }
    }
}
