//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int MsgId { get; set; }
        public short type { get; set; }
        public System.DateTime OnDate { get; set; }
        public string SenderId { get; set; }
        public string ReceiverId { get; set; }
        public string Category { get; set; }
        public string Subject { get; set; }
        public string MsgBody { get; set; }
        public short status { get; set; }
        public Nullable<int> RefMsgId { get; set; }
    }
}
