//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class portfolio
    {
        public portfolio()
        {
            this.investorStocks = new HashSet<investorStock>();
            this.transactions = new HashSet<transaction>();
            this.portfolioDetails = new HashSet<portfolioDetail>();
            this.tradeAlerts = new HashSet<tradeAlert>();
        }
    
        public byte type { get; set; }
        public string code { get; set; }
        public string investorCode { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public decimal startCapAmt { get; set; }
        public decimal usedCapAmt { get; set; }
        public decimal stockAccumulatePerc { get; set; }
        public decimal stockReducePerc { get; set; }
        public decimal maxBuyAmtPerc { get; set; }
        public string interestedStock { get; set; }
        public string interestedSector { get; set; }
    
        public virtual investor investor { get; set; }
        public virtual ICollection<investorStock> investorStocks { get; set; }
        public virtual ICollection<transaction> transactions { get; set; }
        public virtual ICollection<portfolioDetail> portfolioDetails { get; set; }
        public virtual ICollection<tradeAlert> tradeAlerts { get; set; }
    }
}
