//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockCode
    {
        public stockCode()
        {
            this.bestStrategies = new HashSet<bestStrategy>();
            this.investorStocks = new HashSet<investorStock>();
            this.priceDatas = new HashSet<priceData>();
            this.priceDataSums = new HashSet<priceDataSum>();
            this.transactions = new HashSet<transaction>();
            this.stockReports = new HashSet<stockReport>();
            this.tradeAlerts = new HashSet<tradeAlert>();
        }
    
        public string code { get; set; }
        public string stockExchange { get; set; }
        public string tickerCode { get; set; }
        public string name { get; set; }
        public string nameEn { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public string email { get; set; }
        public string bizSectors { get; set; }
        public string country { get; set; }
        public System.DateTime regDate { get; set; }
        public int noListedStock { get; set; }
        public int noOutstandingStock { get; set; }
        public int noForeignOwnedStock { get; set; }
        public int noTreasuryStock { get; set; }
        public decimal bookPrice { get; set; }
        public decimal targetPrice { get; set; }
        public decimal targetPriceVariant { get; set; }
        public decimal workingCap { get; set; }
        public string capitalUnit { get; set; }
        public decimal sales { get; set; }
        public decimal profit { get; set; }
        public decimal equity { get; set; }
        public decimal totalDebt { get; set; }
        public decimal totaAssets { get; set; }
        public decimal PB { get; set; }
        public decimal EPS { get; set; }
        public decimal PE { get; set; }
        public decimal ROA { get; set; }
        public decimal ROE { get; set; }
        public decimal BETA { get; set; }
        public byte status { get; set; }
        public string Headquarter { get; set; }
    
        public virtual ICollection<bestStrategy> bestStrategies { get; set; }
        public virtual ICollection<investorStock> investorStocks { get; set; }
        public virtual ICollection<priceData> priceDatas { get; set; }
        public virtual ICollection<priceDataSum> priceDataSums { get; set; }
        public virtual ICollection<transaction> transactions { get; set; }
        public virtual stockExchange stockExchange1 { get; set; }
        public virtual ICollection<stockReport> stockReports { get; set; }
        public virtual ICollection<tradeAlert> tradeAlerts { get; set; }
    }
}
