//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stockEntities : DbContext
    {
        public stockEntities()
            : base("name=stockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bestStrategy> bestStrategies { get; set; }
        public DbSet<dtproperty> dtproperties { get; set; }
        public DbSet<exchangeDetail> exchangeDetails { get; set; }
        public DbSet<financialModel> financialModels { get; set; }
        public DbSet<investor> investors { get; set; }
        public DbSet<investorStock> investorStocks { get; set; }
        public DbSet<message> messages { get; set; }
        public DbSet<portfolio> portfolios { get; set; }
        public DbSet<portfolioDetail> portfolioDetails { get; set; }
        public DbSet<priceData> priceDatas { get; set; }
        public DbSet<priceDataSum> priceDataSums { get; set; }
        public DbSet<stockCode> stockCodes { get; set; }
        public DbSet<stockExchange> stockExchanges { get; set; }
        public DbSet<stockReport> stockReports { get; set; }
        public DbSet<sysAutoKey> sysAutoKeys { get; set; }
        public DbSet<sysAutoKeyPending> sysAutoKeyPendings { get; set; }
        public DbSet<sysCode> sysCodes { get; set; }
        public DbSet<sysCodeCat> sysCodeCats { get; set; }
        public DbSet<sysConfig> sysConfigs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<sysLog> sysLogs { get; set; }
        public DbSet<tradeAlert> tradeAlerts { get; set; }
        public DbSet<transaction> transactions { get; set; }
    }
}
