//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockExchange
    {
        public stockExchange()
        {
            this.stockCodes = new HashSet<stockCode>();
        }
    
        public string code { get; set; }
        public string description { get; set; }
        public string country { get; set; }
        public string workTime { get; set; }
        public string holidays { get; set; }
        public byte minBuySellDay { get; set; }
        public decimal tranFeePerc { get; set; }
        public decimal priceRatio { get; set; }
        public decimal volumeRatio { get; set; }
        public string dataSource { get; set; }
        public Nullable<byte> weight { get; set; }
        public decimal priceAmplitude { get; set; }
    
        public virtual ICollection<stockCode> stockCodes { get; set; }
    }
}
