//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockReport
    {
        public string reportType { get; set; }
        public string stockCode { get; set; }
        public System.DateTime onDate { get; set; }
        public string reportCode { get; set; }
        public string currency { get; set; }
        public decimal val0 { get; set; }
        public decimal val1 { get; set; }
        public decimal val2 { get; set; }
        public decimal val3 { get; set; }
    
        public virtual stockCode stockCode1 { get; set; }
    }
}
