//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysCode
    {
        public string category { get; set; }
        public string code { get; set; }
        public string inGroup { get; set; }
        public string description1 { get; set; }
        public string description2 { get; set; }
        public Nullable<int> weight { get; set; }
        public string notes { get; set; }
        public string tag1 { get; set; }
        public string tag2 { get; set; }
        public bool isVisible { get; set; }
        public bool isSystem { get; set; }
    
        public virtual sysCodeCat sysCodeCat { get; set; }
    }
}
