//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysCodeCat
    {
        public sysCodeCat()
        {
            this.sysCodes = new HashSet<sysCode>();
        }
    
        public string category { get; set; }
        public string description { get; set; }
        public string notes { get; set; }
        public string tag1 { get; set; }
        public string tag2 { get; set; }
        public bool isVisible { get; set; }
        public bool isSystem { get; set; }
        public Nullable<byte> maxCodeLen { get; set; }
        public Nullable<short> weight { get; set; }
    
        public virtual ICollection<sysCode> sysCodes { get; set; }
    }
}
